openstack::region: 'openstack'

######## Networks
openstack::network::api: '10.22.112.0/22'
openstack::network::external: '192.168.2.0/24'
openstack::network::management: '10.22.112.0/22'
openstack::network::data: '192.168.4.0/24'
openstack::network::data_gateway: '192.168.4.130'

openstack::network::external::ippool::start: 192.168.2.150
openstack::network::external::ippool::end: 192.168.2.200
openstack::network::external::gateway: 192.168.2.1
openstack::network::external::dns: 10.22.75.40

######## Private Neutron Network

openstack::network::neutron::private: '10.33.0.0/16'

######## Fixed IPs (controllers)

openstack::controller::address::api: '10.22.112.131'
openstack::controller::address::management: '10.22.112.131'

openstack::storage::address::api: '10.22.112.132'
openstack::storage::address::management: '10.22.112.132'

######## Database

openstack::mysql::root_password: 'spam-gak'
openstack::mysql::service_password: 'fuva-wax'
openstack::mysql::allowed_hosts: ['localhost', '127.0.0.1', '172.16.33.%', '10.22.113.%','192.168.%','refspec%.vm.labs.scl3.mozilla.com']

######## RabbitMQ

openstack::rabbitmq::user: 'openstack'
openstack::rabbitmq::password: 'pose-vix'

######## Keystone

openstack::keystone::admin_token: 'sosp-kyl'
openstack::keystone::admin_email: 'juber@mozilla.com'
openstack::keystone::admin_password: 'fyby-tet'

openstack::tenants:
    "test":
        description: "Test tenant"
    "test2":
        description: "Test tenant"

openstack::users:
    "test":
        password: "abc123"
        tenant: "test"
        email: "test@example.com"
        admin: true
    "demo":
        password: "abc123"
        tenant: "test"
        email: "demo@example.com"
        admin: false
    "demo2":
        password: "abc123"
        tenant: "test2"
        email: "demo@example.com"
        admin: false

######## Glance

openstack::glance::password: 'na-mu-va'

######## Cinder

openstack::cinder::password: 'zi-co-se'
openstack::cinder::volume_size: '8G'

######## Swift

openstack::swift::password: 'dexc-flo'
openstack::swift::hash_suffix: 'pop-bang'

######## Nova

# kvm needs Hardware Virtualization
openstack::nova::libvirt_type: 'qemu'
openstack::nova::password: 'quuk-paj'

######## Neutron

openstack::neutron::password: 'whi-rtuz'
openstack::neutron::shared_secret: 'by-sa-bo'

######## Ceilometer
openstack::ceilometer::mongo::password: 'whi-truz'
openstack::ceilometer::password: 'whi-truz'
openstack::ceilometer::meteringsecret: 'ceilometersecretkey'

######## Heat
openstack::heat::password: 'zap-bang'
openstack::heat::encryption_key: 'heatsecretkey'


######## Horizon

openstack::horizon::secret_key: 'whu-ghuk'

######## Tempest

openstack::tempest::configure_images    : true
openstack::tempest::image_name          : 'Cirros'
openstack::tempest::image_name_alt      : 'Cirros'
openstack::tempest::username            : 'demo'
openstack::tempest::username_alt        : 'demo2'
openstack::tempest::username_admin      : 'test'
openstack::tempest::configure_network   : true
openstack::tempest::public_network_name : 'public'
openstack::tempest::cinder_available    : true
openstack::tempest::glance_available    : true
openstack::tempest::horizon_available   : true
openstack::tempest::nova_available      : true
openstack::tempest::neutron_available   : true
openstack::tempest::heat_available      : false
openstack::tempest::swift_available     : false

######## Log levels
openstack::verbose: 'True'
openstack::debug: 'False'
